
TYPE
	MainStep_enum : 
		( (*States for the main state machine*)
		MAIN_STARTUP,
		MAIN_POWER_OFF,
		MAIN_DISABLED,
		MAIN_POWER_ON,
		MAIN_GET_SHUTTLE,
		MAIN_GET_SHUTTLE_WAIT,
		MAIN_READY,
		MAIN_START_MOVEMENT,
		MAIN_JOG_SHUTTLE,
		MAIN_WEIGH,
		MAIN_MOVE_6D,
		MAIN_MOVE_ARC,
		MAIN_MOVE_GROUP,
		MAIN_LEVITATE,
		MAIN_HALT_SELECTED,
		MAIN_RESUME_SELECTED,
		MAIN_STOP_SELECTED,
		MAIN_STOP_ALL_SHUTTLES,
		MAIN_RECOVER_ALL,
		MAIN_RECOVER,
		MAIN_ERROR
		);
END_TYPE
